2023-07-08 15:43:21,220 - mongodb_flask.auth - ERROR - User already exists.
2023-07-08 15:43:22,510 - mongodb_flask.auth - INFO - User authenticated successfully: test_user
2023-07-08 15:43:23,592 - mongodb_flask.auth - ERROR - Invalid credentials for username: test_user
